# Generated by Django 5.2.8 on 2025-11-26 02:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exposure', models.FloatField(default=0)),
                ('contrast', models.FloatField(default=0)),
                ('highlights', models.FloatField(default=0)),
                ('shadows', models.FloatField(default=0)),
                ('whites', models.FloatField(default=0)),
                ('blacks', models.FloatField(default=0)),
                ('saturation', models.FloatField(default=0)),
                ('texture', models.FloatField(default=0)),
                ('sharpness', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='originals/')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('operation', models.CharField(choices=[('basic_edit', 'Edição básica'), ('remove_bg', 'Remoção de fundo'), ('inpainting', 'Inpainting / Seleção IA')], max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IALog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('elapsed_ms', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='editor.processedimage')),
            ],
        ),
    ]
