# Generated by Django 5.2.8 on 2025-12-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimage',
            name='selections',
            field=models.TextField(blank=True, null=True),
        ),
    ]
