# Generated by Django 5.2.8 on 2025-12-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preset',
            name='created_at',
        ),
        migrations.AddField(
            model_name='preset',
            name='background_blur',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='preset',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='operation',
            field=models.CharField(choices=[('basic_edit', 'Edição básica'), ('remove_bg', 'Remoção de fundo'), ('inpainting', 'Inpainting / Seleção IA')], max_length=50),
        ),
    ]
